### ISSUE TITLE
Error in the client 

### ISSUE THREAD

**Issue by jedipython** [nftstorage/python-client#4] opened 2022-04-05 21:12 UTC
Error in the python client after the last update on nft.storage
TypeError: _from_openapi_data() missing 1 required positional argument: 'last_change'
What is required to be specified in this argument?

**Comment by dchoi27** [comment] 2022-04-06 17:56
Duplicate of https://github.com/nftstorage/nft.storage/issues/1775

**Comment by alanshaw** [comment] 2022-04-11 14:28
@jedipython any chance you can send a PR to fix...maybe regenerating this using an updated schema will help - https://github.com/nftstorage/nft.storage/blob/main/client-gen.sh

**Comment by dchoi27** [comment] 2022-06-06 15:04
Closing this since we're not supporting this auto-generated Python client

**Closed as completed by dchoi27** 2022-06-06 15:04 UTC
